# Create conversion dictionaries
text_to_morse_dict = {
    'a':'o - -',
    'b':'- o o o',
    'c':'- o - o',
    'd':'- o o',
    'e':'o',
    'f':'o o - o',
    'g':'- - o',
    'h':'o o o o',
    'i':'o o',
    'j':'o - - -',
    'k':'- o -',
    'l':'o - o o',
    'm':'- -',
    'n':'- o',
    'o':'- - -',
    'p':'o - - o',
    'q':'- - o -',
    'r':'o - o',
    's':'o o o',
    't':'-',
    'u':'o o -',
    'v':'o o o -',
    'w':'o - -',
    'x':'- o o -',
    'y':'- o - -',
    'z':'- - o o',
    '1':'o - - - -',
    '2':'o o - - -',
    '3':'o o o - -',
    '4':'o o o o -',
    '5':'o o o o o',
    '6':'- o o o o',
    '7':'- - o o o',
    '8':'- - - o o',
    '9':'- - - - o',
    '0':'- - - - -'
}